FROM ethereum/client-go:v1.13.5

# Créer les répertoires
RUN mkdir -p /root/.ethereum/keystore

# Script d'initialisation
COPY init-geth.sh /root/init-geth.sh
RUN chmod +x /root/init-geth.sh

EXPOSE 8545 8546 30303

ENTRYPOINT ["/root/init-geth.sh"]
